### ISSUE TITLE
hello, can you guide me how to use this library in angular 8?

### ISSUE THREAD

**Issue by azizainunnajib** [bitterbit/flowjs#2]

**Comment by bitterbit** [comment]
Hi @azizainunnajib, I am not sure what exactly do you mean. Try to follow the Usage section in the readme. 

Try to create a `<canvas id="123">` element and then create a new `flowjs.DiFlowChart` object while passing it the id you gave to the canvas. 

Did you try the steps in the readme? what did not work?

**Comment by azizainunnajib** [comment]
hello, sorry for late response.
i found the problem. in your example,

> function simulateLoading(itemId, timeout){
>         setTimeout(function(){
>             flowChart.updateItem(itemId, function(item){
>                 item.flowItem.toggleFlashing();
>             });
>         }, timeout);
>         
>     }

you never mention what is flowChart variable. so i decide to read the library to findout the meaning.
flowChart = new flowjs.DiFlowChart(graph, "canvasID") right?
all fine anyway. but i got 1 more problem. i dont think it is a bug, but more likely new feature.

I create path [["Peter Q", "Gamora", "Nova Prime"], ["Peter Q", "Drax", "Groot",]] so "Peter Q" will have 2 connections. what I want is Line "Peter Q" ----"Gamora" has different color with "Peter Q"----"Drax".

I really hard to try and dont get the solution. I always get ending with conclusion that "the connectors is belongs to the first node, so i can't make 2 color from 1 node." my regard

sorry for my english, i am not really fluent with english..

**Comment by bitterbit** [comment]
`connectors` is an array, you can set the color of `connectors[0]` to blue and `connectors[1]` to red
I did not check this code but modified the code from the example, it should work
```js
flowChart.updateItem(itemId, function(item){
    if (item.connectors === undefined || connectors.length < 2){
        return;
    }
    connectors[0].color = "blue";
    connectors[1].color = "red";
});
```

Hope it helps!

**Comment by azizainunnajib** [comment]
yes, it should be work. I already knew it. but i want more like this happen.

if(next node.id = "gamore") {connector.color = "green"}

I want to change color based on the value of next node id.
in your example, how I know that connector[0] is to Gamora or to Drax??
when i check in console web, I check the object value connector even the next value is 2. but i never try it.

**Comment by bitterbit** [comment]
Ok I think I am starting to understand what you are looking for. 

There is a problem where the connector ui item (`flowConnector`) does not know which id's it connects. 
Additionally the `DiFlowChart` does not keep track of that like it does for flow items.

Seems that what you want to do is still not possible but you are more than welcome to open a new "clean" issue and/or make a pull request to add this feature

Anyway i added some code, maybe it will help you make a "hack" that will work for you.
```js
walker.forEach(function(node){
  if (node.next.includes("gamore"){
    flowChart.updateItem(node.id, function(item){
      // problem: which connector is the one to gamore? 
      item.connectors[index] = "green"
    });
  });
}


```
