### ISSUE TITLE
How to destroy a previously created flowjs chart?

### ISSUE THREAD

**Issue by xCapo95** [bitterbit/flowjs#4]
Hi,
it's probably a stupid question but...
**Is there a function to destroy a previously created flowjs chart?**

(Creating a second graph, with the same variable, I have the impression that something is left dirty)
`var graph = new flowjs.DiGraph();`
`graph.addPaths(obj);`
`var flowChart = new flowjs.DiFlowChart("Flow", graph);`
`flowChart.draw();`

Thanks,
Diego

**Comment by xCapo95** [comment]
I solved it by deleting and recreating the HTML via JQuery.

`$("#Flow").remove();`
`$("#WFFlusso").html("<canvas id='Flow' width='1450' height='500'></canvas>");`

Regards,
Diego

**Comment by bitterbit** [comment]
Hi @xCapo95, I'm happy to see you found a solution :) 
Feel free to ask more questions and share what you are building
